#!/bin/bash

prompt_install() {
	echo -n "$1 is not installed. Would you like to install it? (y/n) " >&2
	while true; do read -n 1 response; if grep -i '[yn]' <<< $response ;then break; fi; done
	if [ $response=="y"] ; then
		if [ -x "$(command -v apt)" ]; then
			sudo apt install $1 -y

		elif [ -x "$(command -v brew)" ]; then
			brew install $1

		elif [ -x "$(command -v pkg)" ]; then
			sudo pkg install $1

		elif [ -x "$(command -v pacman)" ]; then
			sudo pacman -S $1

		else
			echo "Unsupported packet manager" 
		fi 
	fi
}

check_for_software() {
	echo "Checking to see if $1 is installed"
	if ! [ -x "$(command -v $1)" ]; then
		prompt_install $1
	else
		echo "$1 is installed."
	fi
}

echo "Setup of dotfiles:"
echo "Install zsh, vim and tmux (y/n)"
while true; do read -n 1 response; if grep -i '[yn]' <<< $response ;then break; fi; done
if [ $response=="y" ];then
	check_for_software zsh
	check_for_software vim
	check_for_software tmux
	check_for_software git
fi

echo "Checking default shell"
if [ -z "${SHELL##*zsh*}" ] ;then
	echo "ZSH is already default"
else
	echo "ZSH is not the default shell, do you want to set it?"
	while true; do read -n 1 response; if grep -i '[yn]' <<< $response ;then break; fi; done
	if [ $response=="y" ];then
		chsh -s $(which zsh)
	fi
fi

echo "Setup dotfiles (y/n)"
while true; do read -n 1 response; if grep -i '[yn]' <<< $response ;then break; fi; done
if [ $response=="y" ]; then
	echo "source '$HOME/dotfiles/zshrc'" > $HOME/.zshrc
	source $HOME/dotfiles/zshinstallation.sh
fi
