bind h resize-pane -U 10
bind l resize-pane -D 10
bind s setw synchronize-panes
bind j resize-pane -R 5
bind k resize-pane -L 5

set prefix C-a
unbind-key C-b
bind-key C-a send-prefix
bind-key n command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind b command-prompt break-pane 


unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection
