local hop = require("hop")
hop.setup()

vim.keymap.set("n", "<leader>fw", "<cmd>HopWord<CR>")
vim.keymap.set("n", "<leader>fa", "<cmd>HopAnywhere<CR>")
vim.keymap.set("n", "<leader>fc", "<cmd>HopChar1<CR>")
vim.keymap.set("n", "<leader>fl", "<cmd>HopLineStart<CR>")
vim.keymap.set("n", "<leader>fr", "<cmd>HopPattern<CR>")
vim.keymap.set("n", "<leader>fy", "<cmd>HopYankChar1<CR>")
vim.keymap.set("n", "<leader>fp", "<cmd>HopPasteChar1<CR>")
