require("trouble").setup({
	auto_close = false,
	auto_open = false,
	auto_preview = true,
	auto_refresh = true,
	auto_jump = false,
	focus = false,
	restore = true,
	follow = true,
	indent_guides = true,
	max_items = 200,
	multiline = true,
	pinned = false,
	warn_no_results = true,
	open_no_results = false,

	-- Window configuration
	win = {
		size = { height = 10 },
		border = "rounded",
		title = true,
		title_pos = "center",
		zindex = 200,
		wo = {
			winhl = "Normal:TroubleNormal,NormalNC:TroubleNormalNC",
		},
	},

	-- Preview window configuration
	preview = {
		type = "split",
		relative = "win",
		position = "right",
		size = 0.3,
		border = "rounded",
		title = "Preview",
		title_pos = "center",
		wo = {
			winhl = "Normal:TroublePreviewNormal,NormalNC:TroublePreviewNormalNC",
		},
	},

	-- Icons and formatting
	icons = {
		indent = {
			top = "│ ",
			middle = "├╴",
			last = "└╴",
			fold_open = " ",
			fold_closed = " ",
			ws = "  ",
		},
		folder_closed = " ",
		folder_open = " ",
		kinds = {
			Array = " ",
			Boolean = "󰨙 ",
			Class = " ",
			Constant = "󰏿 ",
			Constructor = " ",
			Enum = " ",
			EnumMember = " ",
			Event = " ",
			Field = " ",
			File = " ",
			Function = "󰊕 ",
			Interface = " ",
			Key = " ",
			Method = "󰊕 ",
			Module = " ",
			Namespace = "󰦮 ",
			Null = " ",
			Number = "󰎠 ",
			Object = " ",
			Operator = " ",
			Package = " ",
			Property = " ",
			String = " ",
			Struct = "󰆼 ",
			TypeParameter = " ",
			Variable = "󰀫 ",
		},
	},

	-- Modes configuration
	modes = {
		diagnostics = {
			auto_open = false,
			auto_close = false,
			auto_preview = true,
			auto_refresh = true,
			focus = false,
			follow = true,
			restore = true,
			sort = { "severity", "buf", "pos" },
		},
	},

	-- Keymaps for trouble window
	keys = {
		["?"] = "help",
		r = "refresh",
		R = "toggle_refresh",
		q = "close",
		o = "jump_close",
		["<esc>"] = "cancel",
		["<cr>"] = "jump",
		["<2-leftmouse>"] = "jump",
		["<c-s>"] = "jump_split",
		["<c-v>"] = "jump_vsplit",
		["}"] = "next",
		["]]"] = "next",
		["{"] = "prev",
		["[["] = "prev",
		dd = "delete",
		d = { action = "delete", mode = "v" },
		i = "inspect",
		p = "preview",
		P = "toggle_preview",
		zo = "fold_open",
		zO = "fold_open_recursive",
		zc = "fold_close",
		zC = "fold_close_recursive",
		za = "fold_toggle",
		zA = "fold_toggle_recursive",
		zm = "fold_more",
		zM = "fold_close_all",
		zr = "fold_reduce",
		zR = "fold_open_all",
		zx = "fold_update",
		zX = "fold_update_all",
		zn = "fold_disable",
		zN = "fold_enable",
		zi = "fold_toggle_enable",
	},
})

